var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "xxxx                                                                        xxxx",
   "xxx                                                                          xxx",
   "xxx                                                                          xxx",
   "xxx                                                  o                       xxx",
   "xxx                                                   x                      xxx",
   "xxx                                                                       o  xxx",
   "xxx                                            o                             xxx",
   "xxx                                             x               xx           xxx",
   "xxx                            o              o                              xxx",
   "xxx                             x x x                                        xxx",
   "xxx                                          o                            o  xxx",
   "xxx   @       xxxx      o   xxx                                              xxx",
   "xxx   #       xxxx                                                           xxx",
   "xxxx     xxxxxxxxxxxxxxxxxx           xxxxxxxxxxxx                     xxxxxxxxx",
   "xxxxx   xxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxx                     xxxxxxxxx",
   "xxxxx   xxxxxxxxxxxxxxxxxxx           xxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxx     y     xxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx"],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                  o     xxx                   ",
   "                                  o                                               xx    xx                    ",
   "     @            o           xxx   xxx                                           x     x                     ",
   "     #        xxxxxxxxx        xx   xxxxxx                y                       x     x                     ",
   "             xxxxxxxxxxx        x  xxx                xxxxxx                      x     x     oxxx            ",
   "             xxxxxxxxxxx      o x   xx                x   xx                      x     x     xxx             ",
   "    xxx      xxxxxxxxxxx       xx    xx          xxxxxx o xx                      x     x     xx              ",
   "    xxx      xxxxxxxxxxx      xxxx   xx             xxxx   x                      x    xx     xx            o ",
   "~-~-xxx~-~-~-xxxxxxxxxxx~-~-~xxxx    xxx-~-~-~-~-~-~-~x    x-~-~-~-~-~-~-~-~-~-~-~x  o  x-~-~-xx~-~-~-~-~-~x!x",
   "----xxx------xxxxxxxxxxx-----xxx    xxxx--------------x    xx--------------------xx     x-----xx-----------x!x",
   "----xxx------xxxxxxxxxxx-----xxx   o  xxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxxxxxxx     x-----xx-----------x!x",
   "----xxx------xxxxxxxxxxx-----xxxx        o     o                o                      xx-----xx-----------x!x",
   "----xxx------xxxxxxxxxxx-----xxxxx          o                o     o                  xxx-----xx-----------x!x",
   "----xxx------xxxxxxxxxxx-----xxxxxx                                                  xxxx-----xx-----------x!x",
   "----xxx------xxxxxxxxxxx-----xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-----xx-----------x!x"],
  ["                                                           ",
   "                                                           ",
   "                                                           ",
   " @      o                                                  ",
   " #                                                         ",
   "                                                         o ",
   "xxxx                                                    xxx",
   "xxx                                                     xxx",
   "xx                                                      xxx",
   "xx                                                o xxxxxxx",
   "xx                                          xxxx   xx!!!!!!",
   "xx                                          xxxx   xx!xxxxx",
   "xx                                          xxxx    xvxxxxx",
   "xx                                          xxxx     v  xxx",
   "xx                                          xxxxy        xx",
   "xxxxxxxxoxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx        xx",
   "xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     oxxx",
   "xxxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxx",
   "xxxxxxxx            xxxxxxxx        xxxxxxxxxxxxxx      xxx",
   "xxxxxx               xxxxxx          xxxxxxxxxxxxx       xx",
   "xx                   xxxxxx            xxxxxxxxxxxx      xx",
   "--~                  xxxxxx               xxxxxxxxxxx    xx",
   "---                  xxxxxx                xxxxxxxx      xx",
   "xx-                  xxxxxx                 xxxxxx       xx",
   "xx-                  xxxxxx                   xxxx      xxx",
   "xx-                   xxxx                    xxxx     xxxx",
   "xx-                   xxxx                    xxxx      xxx",
   "xx-                   xxxx                    xxxx       xx",
   "xx-                   xxxx                    xxxxx o    xx",
   "xx-                    xx       o             xxxxxxx    xx",
   "xx-                   oxxo                    xxxxx      xx",
   "xx-                           x               xxxx       xx",
   "xx-               o          xx               xxxx      xxx",
   "xx-               x           xx              xxxx     xxxx",
   "xx-               x          oxx              xxxx      xxx",
   "xx-               xx         xxx              xxxx       xx",
   "xx-              xxx         xxx              xxxxx      xx",
   "xx-              xxx         xxxo             xxxxxxx    xx",
   "xx-             oxxx        xxxxx             xxxxx      xx",
   "xx-             xxxxx       xxxxx             xxxx       xx",
   "xx-             xxxxx       xxxxx             xxxx     oxxx",
   "xx-             xxxxx       xxxxx             xxxx     xxxx",
   "xx-            xxxxxxx     xxxxxxx            xxxx      xxx",
   "xx-      o     xxxxxxx  o  xxxxxxx    o                  xx",
   "xx-     xx    xxxxxxxxx   xxxxxxxxx         o   o        xx",
   "xx-~-~-~xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxx",
   "xx---------------------------------------------------------"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
